<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
    <line>
      <![CDATA[<br><img src='E:\Newtoursmaven\FailedScreenshots\invalidLogin2019-08-04 14-15-46.png' height='400' width='400'/><br>]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="57501" started-at="2019-08-04T12:14:50Z" finished-at="2019-08-04T12:15:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="57501" started-at="2019-08-04T12:14:50Z" finished-at="2019-08-04T12:15:48Z">
      <class name="com.Newtours.Tests.Testcases">
        <test-method status="PASS" signature="launchApp()[pri:0, instance:com.Newtours.Tests.Testcases@e25b2fe]" name="launchApp" is-config="true" duration-ms="12208" started-at="2019-08-04T12:14:50Z" finished-at="2019-08-04T12:15:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method status="PASS" signature="registerUserdetails()[pri:1, instance:com.Newtours.Tests.Testcases@e25b2fe]" name="registerUserdetails" duration-ms="8750" started-at="2019-08-04T12:15:02Z" description="Testcase 1" finished-at="2019-08-04T12:15:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerUserdetails -->
        <test-method status="PASS" signature="login()[pri:2, instance:com.Newtours.Tests.Testcases@e25b2fe]" name="login" duration-ms="24747" started-at="2019-08-04T12:15:11Z" description="Testcase 2" finished-at="2019-08-04T12:15:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="bookFlightdetails()[pri:3, instance:com.Newtours.Tests.Testcases@e25b2fe]" name="bookFlightdetails" duration-ms="7169" started-at="2019-08-04T12:15:36Z" description="Testcase 3" finished-at="2019-08-04T12:15:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bookFlightdetails -->
        <test-method status="FAIL" signature="invalidLogin()[pri:4, instance:com.Newtours.Tests.Testcases@e25b2fe]" name="invalidLogin" duration-ms="2333" started-at="2019-08-04T12:15:43Z" description="Testcase 4" finished-at="2019-08-04T12:15:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://newtours.demoaut.com/mercuryreservation.php] but found [http://newtours.demoaut.com/mercurysignon.php]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://newtours.demoaut.com/mercuryreservation.php] but found [http://newtours.demoaut.com/mercurysignon.php]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.Newtours.Pages.LoginPage.performLogin(LoginPage.java:46)
at com.Newtours.Tests.Testcases.invalidLogin(Testcases.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<br><img src='E:\Newtoursmaven\FailedScreenshots\invalidLogin2019-08-04 14-15-46.png' height='400' width='400'/><br>]]>
            </line>
          </reporter-output>
        </test-method> <!-- invalidLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.Newtours.Tests.Testcases@e25b2fe]" name="tearDown" is-config="true" duration-ms="1330" started-at="2019-08-04T12:15:46Z" finished-at="2019-08-04T12:15:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.Newtours.Tests.Testcases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
